### ISSUE TITLE
Hi,do you have any plans to release the raw videos collected?

### ISSUE THREAD

**Issue by wangqiang9** [wildavatar/WildAvatar_Toolbox#1]

**Comment by wildavatar** [comment]
Thanks for your interest! We are sorry that we cannot release the raw videos directly due to the privacy issue. You can get the video links and annotations from [here](https://zenodo.org/record/11526806/files/WildAvatar.zip), and then download the raw videos and extract images from YouTube, using this [script](https://github.com/wildavatar/WildAvatar_Toolbox/blob/main/prepare_data.py). If you still have any question, feel free to contact us.
